package com.microsoft.foundry.workshop;

import com.azure.ai.agents.persistent.PersistentAgentsClient;
import com.azure.ai.agents.persistent.PersistentAgentsClientBuilder;
import com.azure.ai.agents.persistent.models.CreateAgentOptions;
import com.azure.ai.agents.persistent.models.CreateRunOptions;
import com.azure.ai.agents.persistent.models.MessageRole;
import com.azure.ai.agents.persistent.models.MessageTextContent;
import com.azure.ai.agents.persistent.models.OpenApiAnonymousAuthDetails;
import com.azure.ai.agents.persistent.models.OpenApiFunctionDefinition;
import com.azure.ai.agents.persistent.models.OpenApiToolDefinition;
import com.azure.ai.agents.persistent.models.PersistentAgent;
import com.azure.ai.agents.persistent.models.PersistentAgentThread;
import com.azure.ai.agents.persistent.models.RunStatus;
import com.azure.ai.agents.persistent.models.ThreadMessage;
import com.azure.ai.agents.persistent.models.ThreadRun;
import com.azure.core.credential.TokenCredential;
import com.azure.core.util.BinaryData;
import com.azure.identity.DefaultAzureCredentialBuilder;

import java.util.List;

/**
 * M5 · MCP Tools
 *
 * <p>Goal: connect an agent to a Model Context Protocol (MCP) server and let the
 * model call tools exposed over that protocol.
 *
 * <p>MCP servers expose tools via a standardised JSON-RPC-over-SSE protocol. In Java
 * the recommended approach is to describe the MCP server's tools using an OpenAPI spec
 * and attach it as an {@link OpenApiToolDefinition}. The Foundry agent service routes
 * the tool calls transparently.
 *
 * <p>Run with: {@code mvn exec:java -Dexec.mainClass=com.microsoft.foundry.workshop.Module05McpTools}
 *
 * <p>Prerequisites: set {@code MCP_SERVER_URL} in {@code .env} (optional).
 */
public class Module05McpTools {

    /**
     * Replace with the base URL of your MCP server.
     * For local development: {@code npx @modelcontextprotocol/server-everything}
     * runs on {@code http://localhost:3001} by default.
     */
    private static final String MCP_SERVER_URL = System.getenv()
        .getOrDefault("MCP_SERVER_URL", "http://localhost:3001");

    /**
     * Minimal OpenAPI 3.0 spec describing the MCP server's "get_current_time" tool.
     * Replace with the full spec generated by your MCP server's tool-listing endpoint.
     */
    private static final String MCP_OPENAPI_SPEC = """
        {
          "openapi": "3.0.0",
          "info": { "title": "MCP Tools", "version": "1.0.0" },
          "servers": [{ "url": "%s" }],
          "paths": {
            "/tools/get_current_time": {
              "get": {
                "operationId": "get_current_time",
                "summary": "Get the current UTC time",
                "parameters": [],
                "responses": {
                  "200": {
                    "description": "Current time",
                    "content": {
                      "application/json": {
                        "schema": { "type": "object",
                          "properties": { "utc_time": { "type": "string" } } }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        """;

    public static void main(String[] args) throws InterruptedException {
        WorkshopConfig config = WorkshopConfig.load();

        System.out.println("Project    : " + config.projectEndpoint);
        System.out.println("Chat       : " + config.chatModel);
        System.out.println("MCP server : " + MCP_SERVER_URL);
        System.out.println();

        TokenCredential credential = new DefaultAzureCredentialBuilder().build();
        PersistentAgentsClient client = new PersistentAgentsClientBuilder()
            .endpoint(config.projectEndpoint)
            .credential(credential)
            .buildClient();

        // ── 1. Build an OpenAPI tool backed by the MCP server spec ────────────
        String spec = String.format(MCP_OPENAPI_SPEC, MCP_SERVER_URL);
        OpenApiToolDefinition mcpTool = new OpenApiToolDefinition(
            new OpenApiFunctionDefinition(
                "workshop-mcp",
                BinaryData.fromString(spec),
                new OpenApiAnonymousAuthDetails()
            ).setDescription("Tools exposed by the workshop MCP server.")
        );

        System.out.println("OpenAPI/MCP tool declared: " + mcpTool.getOpenapi().getName());
        System.out.println();

        // ── 2. Create an agent with the MCP/OpenAPI tool ───────────────────────
        PersistentAgent agent = client.getPersistentAgentsAdministrationClient().createAgent(
            new CreateAgentOptions(config.chatModel)
                .setName("mcp-demo-agent")
                .setInstructions("You are a helpful assistant. Use the tools available " +
                    "to you to answer questions. When a tool is relevant, call it.")
                .setTools(List.of(mcpTool))
        );

        System.out.println("Agent created: " + agent.getName());
        System.out.println();

        // ── 3. Invoke via standard thread / run lifecycle ──────────────────────
        System.out.println("=== MCP agent query ===");
        String reply = invokeAgent(client, agent,
            "What is the current time in UTC? Use any available tool to find out.");
        System.out.println(reply);

        client.getPersistentAgentsAdministrationClient().deleteAgent(agent.getId());
    }

    private static String invokeAgent(
            PersistentAgentsClient client, PersistentAgent agent, String userMessage)
            throws InterruptedException {

        PersistentAgentThread thread = client.getThreadsClient().createThread();
        client.getMessagesClient().createMessage(thread.getId(), MessageRole.USER, userMessage);

        ThreadRun run = client.getRunsClient().createRun(
            new CreateRunOptions(thread.getId(), agent.getId())
        );

        while (run.getStatus() == RunStatus.IN_PROGRESS
            || run.getStatus() == RunStatus.QUEUED
            || run.getStatus() == RunStatus.REQUIRES_ACTION) {
            Thread.sleep(1_000);
            run = client.getRunsClient().getRun(thread.getId(), run.getId());
            // OpenAPI tool calls are handled server-side; no client-side dispatch needed.
        }

        if (run.getStatus() != RunStatus.COMPLETED) {
            throw new RuntimeException("Run did not complete: " + run.getStatus());
        }

        for (ThreadMessage msg : client.getMessagesClient().listMessages(thread.getId())) {
            if (msg.getRole() == MessageRole.AGENT) {
                return msg.getContent().stream()
                    .filter(c -> c instanceof MessageTextContent)
                    .map(c -> { MessageTextContent tc = (MessageTextContent) c; return tc.getText().getValue(); })
                    .findFirst().orElse("");
            }
        }
        return "";
    }
}
